#!/usr/bin/env python3
"""
Animation creator for GRChombo simulation plots
Creates GIF animations from the PNG files generated by the plotting script
Enhanced with organized saving and simulation type detection
"""

import os
import glob
import imageio
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
from datetime import datetime

def detect_simulation_type():
    """
    Auto-detect the simulation type based on directory structure and files
    
    Returns:
    --------
    str : Simulation type (KerrBH, BinaryBH, ScalarField, etc.)
    """
    # Check current directory and parent directories for clues
    cwd = os.getcwd()
    
    # Method 1: Check if we're in a specific example directory
    if "KerrBH" in cwd:
        return "KerrBH"
    elif "BinaryBH" in cwd:
        return "BinaryBH"
    elif "ScalarField" in cwd:
        return "ScalarField"
    elif "Cosmo" in cwd:
        return "Cosmology"
    
    # Method 2: Check for characteristic files
    characteristic_files = {
        "KerrBH": ["KerrBH*.hdf5", "Kerr*.dat", "*Kerr*"],
        "BinaryBH": ["BinaryBH*.hdf5", "puncture*.dat", "*Binary*", "*puncture*"],
        "ScalarField": ["ScalarField*.hdf5", "*scalar*", "*potential*"],
        "Cosmology": ["*cosmo*", "*expansion*", "*hubble*"]
    }
    
    for sim_type, patterns in characteristic_files.items():
        for pattern in patterns:
            if glob.glob(pattern, recursive=True) or glob.glob(f"../{pattern}", recursive=True):
                return sim_type
    
    # Method 3: Check data file naming patterns
    png_files = glob.glob("*/*.png")
    if png_files:
        file_names = " ".join([os.path.basename(f) for f in png_files[:5]])  # Sample first few files
        if "Kerr" in file_names:
            return "KerrBH"
        elif "Binary" in file_names:
            return "BinaryBH"
        elif "Scalar" in file_names:
            return "ScalarField"
    
    # Method 4: Check current directory name
    current_dir = os.path.basename(cwd)
    if "kerr" in current_dir.lower():
        return "KerrBH"
    elif "binary" in current_dir.lower():
        return "BinaryBH"
    elif "scalar" in current_dir.lower():
        return "ScalarField"
    
    # Default fallback
    return "GRChombo"

def create_output_directory(sim_type, base_dir=None):
    """
    Create organized output directory for animations
    
    Parameters:
    -----------
    sim_type : str
        Type of simulation
    base_dir : str, optional
        Base directory for output (default: current directory)
        
    Returns:
    --------
    str : Path to created output directory
    """
    if base_dir is None:
        base_dir = os.getcwd()
    
    # Create main animation directory
    animation_dir = f"{sim_type}_animations"
    full_path = os.path.join(base_dir, animation_dir)
    
    if not os.path.exists(full_path):
        os.makedirs(full_path)
        print(f"Created animation directory: {full_path}")
    
    # Create timestamp subdirectory for this run
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir = os.path.join(full_path, f"run_{timestamp}")
    os.makedirs(run_dir, exist_ok=True)
    
    return run_dir

def save_animation_metadata(output_dir, field_names, sim_type, total_animations):
    """
    Save metadata about the animation creation
    
    Parameters:
    -----------
    output_dir : str
        Output directory path
    field_names : list
        List of field names that were animated
    sim_type : str
        Simulation type
    total_animations : int
        Number of animations created
    """
    metadata_file = os.path.join(output_dir, "animation_info.txt")
    
    with open(metadata_file, 'w') as f:
        f.write(f"GRChombo Animation Creation Report\n")
        f.write(f"==================================\n\n")
        f.write(f"Creation Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Simulation Type: {sim_type}\n")
        f.write(f"Working Directory: {os.getcwd()}\n")
        f.write(f"Output Directory: {output_dir}\n\n")
        f.write(f"Animation Summary:\n")
        f.write(f"Total Animations Created: {total_animations}\n")
        f.write(f"Fields Animated: {', '.join(field_names)}\n")
        f.write(f"Source PNG files remain in their original directories\n\n")
        f.write(f"Individual Animations:\n")
        for field in field_names:
            gif_file = f"animation_{field}_{sim_type}.gif"
            if os.path.exists(os.path.join(output_dir, gif_file)):
                file_size = os.path.getsize(os.path.join(output_dir, gif_file)) / (1024*1024)  # MB
                f.write(f"  - {gif_file} ({file_size:.1f} MB)\n")
    
    print(f"Animation metadata saved to: {metadata_file}")

def is_time_series_directory(directory):
    """
    Check if a directory contains time series data suitable for animation
    
    Parameters:
    -----------
    directory : str
        Directory name to check
    
    Returns:
    --------
    bool : True if directory contains time series data
    """
    # Skip directories that are not field evolution data
    skip_dirs = ['gw_plots', 'gw_data', 'venv', '__pycache__', '.git', 'data', 
                 'KerrBH_animations', 'BinaryBH_animations', 'ScalarField_animations', 
                 'GRChombo_animations', 'Cosmology_animations']
    
    if directory in skip_dirs:
        return False
    
    # Check if directory contains PNG files with time series naming pattern
    png_files = glob.glob(f"{directory}/*.png")
    if len(png_files) < 2:  # Need at least 2 images for animation
        return False
    
    # Check if files follow time series pattern (contain timestep info)
    time_series_patterns = ['_000', 'Chk_', 'Plot_', '_t', 'step']
    has_time_pattern = any(pattern in ' '.join(png_files) for pattern in time_series_patterns)
    
    return has_time_pattern

def get_available_fields(plots_dir):
    """
    Get all available field directories that contain PNG files suitable for animation
    
    Returns:
    --------
    list : Available field names
    """
    available_fields = []
    
    # Look for directories that contain PNG files
    for item in os.listdir(plots_dir):
        full_path = os.path.join(plots_dir, item)
        if os.path.isdir(full_path):
            if is_time_series_directory(item):
                available_fields.append(item)
    
    return sorted(available_fields)

def check_image_compatibility(png_files):
    """
    Check if all images in the list have the same dimensions
    
    Parameters:
    -----------
    png_files : list
        List of PNG file paths
    
    Returns:
    --------
    bool : True if all images have same dimensions
    """
    if len(png_files) < 2:
        return True
    
    # Check first two images
    try:
        img1 = imageio.imread(png_files[0])
        img2 = imageio.imread(png_files[1])
        return img1.shape == img2.shape
    except Exception:
        return False

def create_animation(field_name, plots_dir, output_dir=None, sim_type=None, duration=0.2):
    """
    Create GIF animation from PNG files with organized saving
    
    Parameters:
    -----------
    field_name : str
        Name of the field directory (chi, lapse, K, etc.)
    plots_dir : str
        The directory where the 'plots_*' subdirectories are located.
    output_dir : str, optional
        Output directory (auto-created if None)
    sim_type : str, optional
        Simulation type (auto-detected if None)
    duration : float
        Duration per frame in seconds
        
    Returns:
    --------
    str : Path to created animation file, or None if failed
    """
    
    # Auto-detect simulation type if not provided
    if sim_type is None:
        sim_type = detect_simulation_type()
    
    # Create output directory if not provided
    if output_dir is None:
        output_dir = create_output_directory(sim_type)
    
    # Construct the path to the specific field's plot directory
    field_plot_dir = os.path.join(plots_dir, field_name)

    # Check if field directory exists
    if not os.path.exists(field_plot_dir):
        available_fields = get_available_fields(plots_dir)
        print(f"Directory '{field_plot_dir}' not found!")
        print(f"Available field directories in '{plots_dir}': {available_fields}")
        return None
    
    # Check if it's a time series directory
    if not is_time_series_directory(field_plot_dir):
        print(f"Directory '{field_plot_dir}' doesn't contain time series data suitable for animation.")
        print("Skipping this directory.")
        return None
    
    # Get all PNG files and sort them numerically
    png_files = sorted(glob.glob(f"{field_plot_dir}/*.png"))
    
    if not png_files:
        print(f"No PNG files found in {field_plot_dir}/")
        return None
    
    if len(png_files) < 2:
        print(f"Need at least 2 images for animation. Found {len(png_files)} in {field_plot_dir}/")
        return None
    
    # Check image compatibility
    if not check_image_compatibility(png_files):
        print(f"Images in {field_plot_dir}/ have different dimensions. Cannot create animation.")
        return None
    
    print(f"Found {len(png_files)} images for {field_name}")
    
    # Set output filename
    output_filename = f"animation_{field_name}_{sim_type}.gif"
    output_path = os.path.join(output_dir, output_filename)
    
    # Read images and create animation
    images = []
    try:
        for i, filename in enumerate(png_files):
            print(f"Processing {i+1}/{len(png_files)}: {os.path.basename(filename)}")
            img = imageio.imread(filename)
            images.append(img)
        
        # Save as GIF
        print(f"Creating animation: {output_path}")
        imageio.mimsave(output_path, images, duration=duration)
        
        # Get file size for reporting
        file_size = os.path.getsize(output_path) / (1024*1024)  # MB
        print(f"✅ Animation saved: {output_filename} ({file_size:.1f} MB)")
        
        return output_path
        
    except Exception as e:
        print(f"❌ Error creating animation for {field_name}: {e}")
        print("This might be due to incompatible image formats or sizes.")
        return None

def create_all_animations(plots_dir, output_dir=None, sim_type=None, duration=0.2):
    """
    Create animations for all available field directories with organized saving
    
    Parameters:
    -----------
    plots_dir : str
        The directory where the 'plots_*' subdirectories are located.
    output_dir : str, optional
        Output directory (auto-created if None)
    sim_type : str, optional
        Simulation type (auto-detected if None)
    duration : float
        Duration per frame in seconds
        
    Returns:
    --------
    tuple : (output_directory, list_of_created_animations)
    """
    available_fields = get_available_fields(plots_dir)
    
    if not available_fields:
        print(f"No field directories with time series PNG files found in '{plots_dir}'!")
        print("Run the plotting script first.")
        return None, []
    
    # Auto-detect simulation type if not provided
    if sim_type is None:
        sim_type = detect_simulation_type()
    
    # Create output directory if not provided
    if output_dir is None:
        output_dir = create_output_directory(sim_type)
    
    print(f"🎬 Creating {sim_type} Animations")
    print(f"Output directory: {output_dir}")
    print(f"Looking for plots in: {plots_dir}")
    print(f"Found {len(available_fields)} time series field directories: {available_fields}")
    print("Creating animations for all fields...\n")
    
    successful_animations = []
    failed_fields = []
    
    for field in available_fields:
        print(f"--- Creating animation for {field} ---")
        try:
            animation_path = create_animation(field, plots_dir, output_dir, sim_type, duration)
            if animation_path:
                successful_animations.append(animation_path)
            else:
                failed_fields.append(field)
        except Exception as e:
            print(f"❌ Failed to create animation for {field}: {e}")
            failed_fields.append(field)
    
    # Save metadata
    save_animation_metadata(output_dir, [os.path.splitext(os.path.basename(p))[0].replace(f"animation_", "").replace(f"_{sim_type}", "") for p in successful_animations], sim_type, len(successful_animations))
    
    # Final report
    print(f"\n🎉 Animation creation completed!")
    print(f"✅ Successfully created: {len(successful_animations)}/{len(available_fields)} animations")
    if failed_fields:
        print(f"❌ Failed: {failed_fields}")
    print(f"📂 All animations saved in: {output_dir}")
    print(f"📁 Source PNG files remain in their original directories")
    
    return output_dir, successful_animations

def show_sample_plot(field_name, timestep=0):
    """
    Display a sample plot
    
    Parameters:
    -----------
    field_name : str
        Name of the field (chi, lapse, K, etc.)
    timestep : int
        Which timestep to show (0 = first, -1 = last)
    """
    
    # This function currently assumes plots are in the current directory.
    # If plots_dir is passed, it should be used here.
    # For now, keeping it as is, but it might need adjustment if plots_dir is always passed.
    plots_dir = os.getcwd() # Default to current directory

    if not os.path.exists(field_name):
        available_fields = get_available_fields(plots_dir)
        print(f"Directory '{field_name}' not found!")
        print(f"Available field directories in '{plots_dir}': {available_fields}")
        return
    
    png_files = sorted(glob.glob(f"{field_name}/*.png"))
    
    if not png_files:
        print(f"No PNG files found in {field_name}/")
        return
    
    # Select file
    if timestep == -1:
        selected_file = png_files[-1]
    else:
        timestep = min(timestep, len(png_files)-1)
        selected_file = png_files[timestep]
    
    print(f"Displaying: {selected_file}")
    
    # Load and display image
    img = mpimg.imread(selected_file)
    plt.figure(figsize=(10, 8))
    plt.imshow(img)
    plt.axis('off')
    
    # Auto-detect simulation type for title
    sim_type = detect_simulation_type()
    plt.title(f"{sim_type} Simulation - {field_name.upper()} field\n{os.path.basename(selected_file)}")
    plt.tight_layout()
    plt.show()

def list_available_fields():
    """
    List all available field directories and their contents
    """
    # This function currently assumes plots are in the current directory.
    # If plots_dir is passed, it should be used here.
    # For now, keeping it as is, but it might need adjustment if plots_dir is always passed.
    plots_dir = os.getcwd() # Default to current directory

    available_fields = get_available_fields(plots_dir)
    
    if not available_fields:
        print("No field directories with time series PNG files found!")
        return
    
    sim_type = detect_simulation_type()
    print(f"🔍 {sim_type} Simulation - Available time series field directories:")
    for field in available_fields:
        png_files = glob.glob(f"{field}/*.png")
        print(f"  - {field}: {len(png_files)} plots")
    
    # Also show non-time series directories
    all_dirs = [d for d in os.listdir(plots_dir) if os.path.isdir(os.path.join(plots_dir, d)) and d not in ['venv', '__pycache__', '.git']]
    non_time_series = [d for d in all_dirs if not is_time_series_directory(d) and glob.glob(f"{os.path.join(plots_dir, d)}/*.png")]
    
    if non_time_series:
        print("\n📊 Directories with plots (not suitable for animation):")
        for field in non_time_series:
            png_files = glob.glob(f"{field}/*.png")
            print(f"  - {field}: {len(png_files)} plots (static analysis)")

def main():
    """Main function with command line interface"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Create organized animations from GRChombo simulation plots')
    parser.add_argument('field', nargs='?', help='Field name (chi, lapse, K, etc.) or "all" for all fields')
    parser.add_argument('--output', '-o', help='Custom output directory')
    parser.add_argument('--sim-type', help='Simulation type (auto-detected if not specified)')
    parser.add_argument(
        '--plots_dir', 
        type=str, 
        default='.', 
        help='The directory containing the "plots_*" folders. Defaults to the current directory.'
    )
    parser.add_argument('--duration', '-d', type=float, default=0.2, 
                       help='Duration per frame (seconds)')
    parser.add_argument('--show', '-s', action='store_true', 
                       help='Show a sample plot instead of creating animation')
    parser.add_argument('--timestep', '-t', type=int, default=0,
                       help='Timestep to show (for --show option)')
    parser.add_argument('--list', '-l', action='store_true',
                       help='List available field directories')
    
    args = parser.parse_args()
    
    if args.list:
        list_available_fields()
        return
    
    if not args.field:
        # If no field specified, show available fields and create all animations
        print("No field specified. Available options:")
        list_available_fields()
        print(f"\n🎬 Creating animations for all available time series fields...")
        output_dir, animations = create_all_animations(
            plots_dir=args.plots_dir,
            output_dir=args.output, 
            sim_type=args.sim_type,
            duration=args.duration
        )
        return
    
    if args.field.lower() == 'all':
        output_dir, animations = create_all_animations(
            plots_dir=args.plots_dir,
            output_dir=args.output,
            sim_type=args.sim_type, 
            duration=args.duration
        )
        return
    
    if args.show:
        show_sample_plot(args.field, args.timestep)
    else:
        sim_type = args.sim_type or detect_simulation_type()
        output_dir = args.output or create_output_directory(sim_type)
        animation_path = create_animation(
            args.field,
            plots_dir=args.plots_dir,
            output_dir=output_dir, 
            sim_type=sim_type, 
            duration=args.duration
        )
        if animation_path:
            print(f"🎉 Animation created: {animation_path}")

if __name__ == "__main__":
    main() 