#!/usr/bin/env python3
"""
Animation creator for Binary Black Hole simulation plots
Creates GIF animations from the PNG files generated by the plotting script
"""

import os
import glob
import imageio
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def create_animation(field_name, output_filename=None, duration=0.2):
    """
    Create GIF animation from PNG files
    
    Parameters:
    -----------
    field_name : str
        Name of the field directory (chi, lapse, K, etc.)
    output_filename : str, optional
        Output GIF filename. If None, auto-generated
    duration : float
        Duration per frame in seconds
    """
    
    # Check if field directory exists
    if not os.path.exists(field_name):
        print(f"Directory '{field_name}' not found!")
        print(f"Available directories: {[d for d in os.listdir('.') if os.path.isdir(d)]}")
        return
    
    # Get all PNG files and sort them numerically
    png_files = sorted(glob.glob(f"{field_name}/*.png"))
    
    if not png_files:
        print(f"No PNG files found in {field_name}/")
        return
    
    print(f"Found {len(png_files)} images for {field_name}")
    
    # Set output filename
    if output_filename is None:
        output_filename = f"animation_{field_name}_BinaryBH.gif"
    
    # Read images and create animation
    images = []
    for i, filename in enumerate(png_files):
        print(f"Processing {i+1}/{len(png_files)}: {os.path.basename(filename)}")
        images.append(imageio.imread(filename))
    
    # Save as GIF
    print(f"Creating animation: {output_filename}")
    imageio.mimsave(output_filename, images, duration=duration)
    print(f"Animation saved as {output_filename}")

def show_sample_plot(field_name, timestep=0):
    """
    Display a sample plot
    
    Parameters:
    -----------
    field_name : str
        Name of the field (chi, lapse, K)
    timestep : int
        Which timestep to show (0 = first, -1 = last)
    """
    
    if not os.path.exists(field_name):
        print(f"Directory '{field_name}' not found!")
        return
    
    png_files = sorted(glob.glob(f"{field_name}/*.png"))
    
    if not png_files:
        print(f"No PNG files found in {field_name}/")
        return
    
    # Select file
    if timestep == -1:
        selected_file = png_files[-1]
    else:
        timestep = min(timestep, len(png_files)-1)
        selected_file = png_files[timestep]
    
    print(f"Displaying: {selected_file}")
    
    # Load and display image
    img = mpimg.imread(selected_file)
    plt.figure(figsize=(10, 8))
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Binary Black Hole - {field_name.upper()} field\n{os.path.basename(selected_file)}")
    plt.tight_layout()
    plt.show()

def main():
    """Main function with command line interface"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Create animations from Binary BH plots')
    parser.add_argument('field', help='Field name (chi, lapse, K)')
    parser.add_argument('--output', '-o', help='Output filename')
    parser.add_argument('--duration', '-d', type=float, default=0.2, 
                       help='Duration per frame (seconds)')
    parser.add_argument('--show', '-s', action='store_true', 
                       help='Show a sample plot instead of creating animation')
    parser.add_argument('--timestep', '-t', type=int, default=0,
                       help='Timestep to show (for --show option)')
    
    args = parser.parse_args()
    
    if args.show:
        show_sample_plot(args.field, args.timestep)
    else:
        create_animation(args.field, args.output, args.duration)

if __name__ == "__main__":
    # If run without arguments, create animations for all available fields
    available_fields = [d for d in ['chi', 'lapse', 'K'] if os.path.exists(d)]
    
    if available_fields:
        print("Creating animations for available fields...")
        for field in available_fields:
            create_animation(field)
        print("\nAnimations completed!")
    else:
        print("No field directories found. Run the plotting script first.")
        print("Usage: python create_animation.py <field_name>")
        print("       python create_animation.py chi --show  # to view a sample plot") 